name: Traffic Stats

on:
  schedule:
    - cron: "0 23 * * *" # 每天跑一次
  workflow_dispatch:     # 允許手動執行

jobs:
  traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Repository Traffic
        uses: sangonzal/repository-traffic-action@v1
        with:
          # 注意：這裡的參數名稱不一樣，是 github_token
          github_token: ${{ secrets.GH_TOKEN }}
